import Head from 'next/head'
import { DataItineraio } from '../../datos-paginas/itineario'
import styles from './styles.module.scss'

export const Index = () => {
  return (
    <>
      <Head>
        <title>Políticas de Itinerario - Enlace mundial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/hamburgers/1.1.3/hamburgers.min.css"
        />
      </Head>
      <section className={`${styles.terminos} container mt-5`}>
        <div className="row">
          <div className="col-md-12 text-center mb-4">
            <h1 className="font-weight-bold">POLÍTICAS DE ITINERARIO</h1>
          </div>
          {DataItineraio &&
            DataItineraio.map((item, index) => (
              <article className="col-md-12 item mb-5 px-0" key={index}>
                <p className="mb-4">{item}</p>
              </article>
            ))}
        </div>
      </section>
    </>
  )
}
export default Index
