import react, { useEffect, useState } from "react"
import Link from "next/link"
import Moment from "react-moment"
import tours from "../../../datos-paginas/api/tours"
import Head from "next/head"
import styles from "./styles.module.scss"

// Components
import SidebarCuenta from "@/components/mi-cuenta/sidebar"
import { useOrdenServices } from "../../../gestion-de-endpoints/useOrdenServices"

export default function MiCuenta() {
  const [items, setItems] = useState([])

  const { dataOrden, loadingGetData } = useOrdenServices()

  useEffect(() => {
    !loadingGetData && setItems(dataOrden?.data)
  }, [loadingGetData])

  return (
    <>
      <Head>
        <title> Enlace mundial</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/hamburgers/1.1.3/hamburgers.min.css'
        />
      </Head>
      <section className={`${styles.reservas} container mt-4 mt-md-5`}>
        <div className='row justify-content-around'>
          <div className='col-md-4'>
            <SidebarCuenta />
          </div>

          <div className='col-md-8 col-xl-7 mt-4 mt-md-0'>
            <div className='p-3 shadow-card'>
              <h3 className='subtitulo-general font-weight-bold text-left'>
                Mis reservaciones
              </h3>

              <section className='mt-3 mx-2'>
                {items
                  ? items.map((item, index) => {
                      return (
                        <div
                          key={index}
                          className={`${styles.card_reserva} card bg-light border-0 mt-3 rounded `}
                        >
                          <div className=' p-3 d-flex justify-content-center flex-column align-items-center '>
                            <h4 className='card-title text-md ml-4'>
                              {item.Pasajes[0].tituloTour}
                            </h4>
                            <div className='d-flex justify-content-lg-between  flex-column flex-lg-row  justify-content-center '>
                              <div className='d-flex  flex-column flex-lg-row align-items-center '>
                                <div className='col-md-6 d-flex justify-content-center '>
                                  <img
                                    src={
                                      item.Pasajes[0].Tour.imagenPrincipalTour
                                        .url
                                    }
                                    className={`${styles.reservas_imagen} `}
                                  />
                                </div>
                                <div className='d-flex align-items-center col-md-6 mt-3 mt-xl-0  justify-content-center'>
                                  <div className='  '>
                                    <div className='d-flex'>
                                      <span className='font-weight-bold '>
                                        Estado:
                                      </span>

                                      <span className='d-inline-block ml-3'>
                                        {item.estadoOrdenTour}
                                      </span>
                                    </div>

                                    <div className='d-flex mt-2'>
                                      <span className='font-weight-bold'>
                                        Fecha:
                                      </span>

                                      <span className='d-inline-block ml-3'>
                                        {item.fechaReserva}
                                      </span>
                                    </div>
                                    <div className='d-flex mt-2'>
                                      <span className='font-weight-bold '>
                                        Personas:
                                      </span>

                                      <span className='d-inline-block ml-3'>
                                        {item.Pasajes.length}
                                      </span>
                                    </div>
                                    <div className='d-flex mt-2 '>
                                      <span className='font-weight-bold '>
                                        Monto:
                                      </span>

                                      <span className='d-inline-block ml-3'>
                                        s/{" "}
                                        {item.Pasajes.reduce(
                                          (total, precio) =>
                                            total + precio.precioTour,
                                          0
                                        )}
                                      </span>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <div className='d-flex align-items-end  justify-content-center'>
                                <div>
                                  <Link
                                    href={`/mi-cuenta/reservas/${item.ordenTourId}`}
                                    passHref
                                  >
                                    <a className='btn btn-outline-primary d-flex align-items-center mt-2 px-3'>
                                      Detalles
                                      <i className='fas fa-chevron-right ml-2'></i>
                                    </a>
                                  </Link>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      )
                    })
                  : ""}
              </section>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}
