import react from "react";
import Head from "next/head";
import Link from "next/link";

import tours from "../../datos-paginas/api/tours";

import styles from "./styles.module.scss";

import { Tabs, Form } from "react-bootstrap";
import Tab from "react-bootstrap/Tab";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Luna de miel - Enlace mundial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/hamburgers/1.1.3/hamburgers.min.css"
        />
      </Head>

      <main className={`${styles.finalizarReserva} mt-5`}>
        <section className="container">
          <div className="row">
            <div className="col-md-8 mt-3 mt-md-0">
              <div className="card shadow-card rounded-0">
                <div className="card-header bg-primary text-white text-uppercase font-weight-bold rounded-0">
                  Finalizar Reserva
                </div>
                <div className="card-body">
                  <Tabs
                    defaultActiveKey="home"
                    id="uncontrolled-tab-example"
                    className="mb-3"
                  >
                    <Tab eventKey="home" title="Datos del comprador">
                      <section className="p-3">
                        <form>
                          <div className="form-row">
                            <div className="col-md-6">
                              <div className="form-group">
                                <label>Nombres</label>
                                <input type="text" className="form-control" />
                              </div>
                            </div>

                            <div className="col-md-6">
                              <div className="form-group">
                                <label>Apellidos</label>
                                <input type="text" className="form-control" />
                              </div>
                            </div>
                          </div>

                          <div className="form-row mt-3">
                            <div className="col-md-6">
                              <div className="form-group">
                                <label>Tipo de documento</label>
                                <select className="form-control">
                                  <option value="DNI">DNI</option>
                                  <option value="CE">
                                    Carnet de extranjería
                                  </option>
                                  <option value="PASAPORTE">Pasaporte</option>
                                </select>
                              </div>
                            </div>

                            <div className="col-md-6">
                              <div className="form-group">
                                <label>Número de documento</label>
                                <input
                                  type="number"
                                  min="0"
                                  step="1"
                                  className="form-control"
                                />
                              </div>
                            </div>
                          </div>

                          <div className="form-row mt-3">
                            <div className="col-md-12">
                              <div className="form-group">
                                <label>Comentarios adicionales</label>
                                <textarea className="form-control"></textarea>
                              </div>

                              <div className="form-group mt-3 px-md-4">
                                <p>
                                  <Form.Check type="checkbox" />
                                  Acepto los{" "}
                                  <Link href="/terminos-y-condiciones">
                                    Términos y Condiciones Generales
                                  </Link>{" "}
                                  de Enlace Mundial
                                </p>
                              </div>
                            </div>
                          </div>

                          <div className="text-right">
                            <button
                              type="button"
                              className="btn btn-primary px-4"
                            >
                              Siguiente
                              <span className="d-inline-block ml-2">
                                <i class="fas fa-chevron-right"></i>
                              </span>
                            </button>
                          </div>
                        </form>
                      </section>
                    </Tab>
                    <Tab eventKey="profile" title="Finalizar pago" disabled>
                      Profile
                    </Tab>
                  </Tabs>
                </div>
              </div>
            </div>

            <div className={`${styles.finalizarReserva_col2} col-md-4`}>
              <div className="card shadow-card">
                <div
                  style={{
                    backgroundImage: "url(" + tours[0].imagenPrincipal + ")",
                  }}
                  className={`${styles.finalizarReserva_imagenTour} bg-info`}
                ></div>
                <div className="card-body">
                  <h2 className="border-bottom pb-2">{tours[0].titulo}</h2>

                  <div className="mt-2 border-bottom pb-3">
                    <span className="text-muted">Fecha de reserva: </span>

                    <div className="row mt-2">
                      <div className="col-md-6">
                        <p>
                          <i class="far fa-calendar-alt"></i>
                          <span className="d-inline-block ml-2">
                            10/09/2021
                          </span>
                        </p>
                      </div>

                      <div className="col-md-6">
                        <p>
                          <i class="far fa-clock"></i>
                          <span className="d-inline-block ml-2">
                            10/09/2021
                          </span>
                        </p>
                      </div>
                    </div>
                  </div>

                  <div className="mt-2 border-bottom pb-3">
                    <span className="text-muted">Pasajeros: </span>

                    <div className="row mt-2">
                      <div className="col-md-6">
                        <p>
                          <i class="fas fa-restroom"></i>
                          <span className="d-inline-block ml-2">
                            10/09/2021
                          </span>
                        </p>
                        <span className="small text-primary">Adultos</span>
                      </div>

                      <div className="col-md-6">
                        <p>
                          <i class="fas fa-child"></i>
                          <span className="d-inline-block ml-2">
                            10/09/2021
                          </span>
                        </p>
                        <span className="small text-primary">Niños</span>
                      </div>
                    </div>
                  </div>

                  <div className="d-flex justify-content-between align-items-center mt-2 pb-3 pr-md-3 border-bottom">
                    <span className="text-muted">TOTAL</span>

                    <h3>S/. 100.00</h3>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
