import React, { useState, useRef } from "react"
import { useRouter } from "next/router"
import Head from "next/head"
import Link from "next/link"
import posts from "../../../datos-paginas/api/blog"
import CardBlog from "@/components/cards/card-blog"
import styles from "../styles.module.scss"
import { GET_ALL_BLOG_CATEGORIA, URL } from "../../../endpoints y url/endpoints"
import request from "graphql-request"

export async function getServerSideProps({ params }) {
  const res = await request(URL, GET_ALL_BLOG_CATEGORIA, {
    slugCategoriaBlog: params.slug,
    estadoBlog: "1",
    numberPaginate: 10,
    page: 1,
  })
  const data = res?.GetAllBlogCategoria?.data

  return {
    props: {
      data: data,
    },
  }
}

export default function Home({ data }) {
  const router = useRouter()

  const [items, setItems] = useState(posts)

  const categoria = {
    id: 1,
    nombre: "Lugares turísticos en Lima",
  }

  let slug = router.query.slug

  const titulo = data === [] ? data[0].CategoriaBlog.tituloCategoriaBlog : slug

  // Swiper
  const swiperRef = useRef(null)

  const carouselParams = {
    slidesPerView: 1,
    loop: true,
  }

  return (
    <div>
      <Head>
        <title>{slug} - Enlace mundial</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/hamburgers/1.1.3/hamburgers.min.css'
        />
      </Head>

      <main className={styles.slug}>
        <section className='l-miel__items mt-4'>
          <div className='container'>
            <div className='row'>
              <div className='col-md-12'>
                <span className='small text-primary'>categorias/{slug}</span>
              </div>
            </div>
          </div>

          {/* Info */}
          <section className='container mt-5'>
            <div className='row'>
              <div className='col'>
                <h2 className={styles.slug_titulo}>Categoria - {titulo}</h2>
              </div>
            </div>
            <div className='row  mt-4 '>
              {data.map((item) => {
                return (
                  <div key={item.blogId} className='col-md-4 my-2'>
                    <CardBlog item={item} />
                  </div>
                )
              })}
            </div>
          </section>
        </section>
      </main>
    </div>
  )
}
