import React, { useEffect, useState } from "react"
import Head from "next/head"
import Select from "react-select"
import Script from "next/script"
import CardBusqueda from "@/components/cards/card-busqueda"
import GestionTours from "../../gestion-de-endpoints/GestionTours"
import { useActividadesServices } from "../../gestion-de-endpoints/useActividadesServices"
import { useIncluyeServices } from "../../gestion-de-endpoints/useIncluyeServices"
import GestionBusqueda from "../../gestion-de-endpoints/GestionBusqueda"
import CategoriasServices from "../../gestion-de-endpoints/useCategoriasServices"

export default function ActividadesYTurismo() {
  const [incluye, setIncluye] = useState("")
  const [actividades, setAactividades] = useState("")
  const [categoria, setCategoria] = useState("")
  const { dataCategoria, loadingCategoria } = CategoriasServices()
  const [busqueda, setBusqueda] = useState({
    fecha_ini: "",
    fecha_fina: "",
    precio_base: "",
    horas: "",
    dias: "",
  })

  const { fecha_ini, fecha_fina, precio_base, horas, dias } = busqueda

  const { db: dataActividades, loadingGetData: loadingActiviades } =
    useActividadesServices()
  const { db: dataIncluye, loadingGetData: loadingIncluye } =
    useIncluyeServices()
  const { dataTours, loading: loadingGetTour } = GestionTours()

  const [itemsTours, setItemsTours] = useState([])
  useEffect(() => {
    if (!loadingGetTour) {
      setItemsTours(dataTours)
    }
  }, [loadingGetTour])

  const { dataBusqueda, getBusquedaAvanzada, loadingBusqueda } =
    GestionBusqueda({
      fecha_ini: fecha_ini,
      fecha_fina: fecha_fina,
      incluye: incluye,
      actividades: actividades,
      categoria_slug: categoria,
      precio_base: "",
      horas: "",
      dias: "",
      page: 1,
      numberPaginate: 12,
    })

  useEffect(() => {
    if (!loadingBusqueda) {
      if (dataBusqueda.length !== 0) {
        setItemsTours(dataBusqueda)
      }
    }
  }, [dataBusqueda])

  useEffect(() => {
    getBusquedaAvanzada()
  }, [fecha_ini, fecha_fina, incluye, actividades, categoria])

  const onChange = (e) => {
    setBusqueda({
      ...busqueda,
      [e.target.name]: e.target.value,
    })
  }

  const quitar = () => {
    setItemsTours(dataTours)
    setBusqueda({
      fecha_ini: "",
      fecha_fina: "",
      categoria_slug: "",
      precio_base: "",
      horas: "",
      dias: "",
    })
    setIncluye("")
    setAactividades("")
  }

  return (
    <div className='busqueda-page'>
      <Head>
        <title>Actividades y turismo - Enlace mundial</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/hamburgers/1.1.3/hamburgers.min.css'
        />
      </Head>

      <main>
        <section className='container mt-5 px-4 px-md-0'>
          <div className='row'>
            <div className='col-12'>
              <div className='d-flex justify-content-between align-items-center'>
                <h3 className='subtitulo-slug text-secondary text-left'>
                  Tours a Cusco (Región Cusco)
                </h3>

                {/* Solo desktop */}
                <div className='d-none d-md-block'>
                  <span className='d-inline-block mr-3'>Crucero</span>
                  <span>Inicio</span>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className='container mt-4 mt-md-5 px-4 px-md-0'>
          <div className='row'>
            <div className='col-md-3'>
              <aside>
                <button
                  type='button'
                  className='btn btn-primary btn-block font-weight-bold'
                  onClick={quitar}
                >
                  Quitar filtros
                </button>

                <div className='card bg-light border-0 rounded-0 mt-4'>
                  <div className='card-body pb-1'>
                    <h3 className='card-title stext-secondary font-weight-bold'>
                      Disponibilidad de salidas
                    </h3>

                    <div className='form-group'>
                      <label htmlFor='fechaInicial' className='text-secondary'>
                        Desde
                      </label>
                      <input
                        type='date'
                        className='form-control rounded-0'
                        value={fecha_ini}
                        name='fecha_ini'
                        onChange={onChange}
                      />
                    </div>

                    <div className='form-group'>
                      <label htmlFor='fechaInicial' className='text-secondary'>
                        Hasta
                      </label>
                      <input
                        type='date'
                        className='form-control rounded-0'
                        value={fecha_fina}
                        name='fecha_fina'
                        onChange={onChange}
                      />
                    </div>
                  </div>
                </div>

                <div className='mt-4'>
                  {loadingCategoria ? (
                    <p>Cargando ...</p>
                  ) : (
                    dataCategoria.map((categoria) => {
                      return (
                        <div
                          className='form-check'
                          key={categoria?.categoriaId}
                        >
                          <input
                            className='form-check-input'
                            type='radio'
                            name={categoria}
                            onClick={() =>
                              setCategoria(categoria?.slugCategoria)
                            }
                            value={categoria?.tituloCategoria}
                            id={categoria?.categoriaId}
                          />
                          <label
                            className='form-check-label'
                            htmlFor={categoria?.categoriaId}
                          >
                            {categoria?.tituloCategoria}
                          </label>
                        </div>
                      )
                    })
                  )}
                </div>

                {/* Solo desktop */}
                <section className='mt-4 d-none d-md-block'>
                  <h4 className='card-subtitle font-weight-bold'>
                    Tours de último minuto
                  </h4>

                  <div className='mt-3'>
                    <div className='form-check'>
                      <input
                        className='form-check-input'
                        type='radio'
                        name='disponibles'
                        id='disponible-1'
                        value='option1'
                      />
                      <label
                        className='form-check-label text-muted'
                        htmlFor='disponible-1'
                      >
                        Disponibles hoy o mañana
                      </label>
                    </div>

                    <div className='form-check'>
                      <input
                        className='form-check-input'
                        type='radio'
                        name='disponibles'
                        id='disponible-2'
                        value='option1'
                      />
                      <label
                        className='form-check-label text-muted'
                        htmlFor='disponible-2'
                      >
                        Disponibles hoy o mañana o pasado
                      </label>
                    </div>
                  </div>

                  <div className='mt-3'>
                    {/* <h3 className='card-title stext-secondary font-weight-bold'>
                      Destinos en Perú
                    </h3>

                    <h3 className='card-title stext-secondary font-weight-bold'>
                      Perú
                    </h3>

                    <div className='form-check'>
                      <input
                        className='form-check-input'
                        type='checkbox'
                        value=''
                        id='destino-padre'
                      />
                      <label
                        className='form-check-label'
                        htmlFor='destino-padre'
                      >
                        Cusco
                      </label>
                    </div>

                    <div className='mt-1 px-3'>
                      <div className='form-check'>
                        <input
                          className='form-check-input'
                          type='checkbox'
                          value=''
                          id='destino-hijo'
                        />
                        <label
                          className='form-check-label'
                          htmlFor='destino-hijo'
                        >
                          Tours a Cusco
                        </label>
                      </div>
                    </div> */}

                    {/* Incluye */}
                    <h3 className='card-title stext-secondary font-weight-bold mt-3'>
                      Incluye
                    </h3>

                    {loadingIncluye ? (
                      <p>Cargando ...</p>
                    ) : (
                      dataIncluye.map((incluye) => {
                        return (
                          <div className='form-check' key={incluye?.incluyeId}>
                            <input
                              className='form-check-input'
                              type='radio'
                              name={incluye}
                              onClick={() => setIncluye(incluye?.incluyeId)}
                              value={incluye?.descripcionIncluye}
                              id={incluye?.incluyeId}
                            />
                            <label
                              className='form-check-label'
                              htmlFor={incluye?.incluyeId}
                            >
                              {incluye?.descripcionIncluye}
                            </label>
                          </div>
                        )
                      })
                    )}

                    {/* Actividades */}
                    <h3 className='card-title stext-secondary font-weight-bold mt-3'>
                      Actividades
                    </h3>
                    {loadingActiviades ? (
                      <p>Cargando ...</p>
                    ) : (
                      dataActividades.map((actividad) => {
                        return (
                          <div
                            className='form-check'
                            key={actividad?.actividadId}
                          >
                            <input
                              className='form-check-input'
                              type='radio'
                              name='actividad'
                              onClick={() =>
                                setAactividades(actividad?.actividadId)
                              }
                              value={actividad?.descripcion_actividad}
                              id={actividad?.actividadId}
                            />
                            <label
                              className='form-check-label'
                              htmlFor={actividad?.actividadId}
                            >
                              {actividad?.descripcion_actividad}
                            </label>
                          </div>
                        )
                      })
                    )}
                  </div>
                </section>
              </aside>
            </div>

            <div className='col-md-9 mt-4 mt-md-0'>
              {itemsTours.length !== 0 ? (
                itemsTours.map((item) => {
                  return <CardBusqueda item={item} key={item.tourId} />
                })
              ) : (
                <p>No hay Resultados</p>
              )}
            </div>
          </div>
        </section>
        <div className='hidden'></div>
      </main>

      <Script
        src='https://kit.fontawesome.com/3bd84f9f96.js'
        crossorigin='anonymous'
      />
    </div>
  )
}
