import React, { useEffect, useState } from "react"
import Head from "next/head"
import Script from "next/script"
import CardBusqueda from "@/components/cards/card-busqueda"
import GestionTours from "../../gestion-de-endpoints/GestionTours"
import { useActividadesServices } from "../../gestion-de-endpoints/useActividadesServices"
import { useIncluyeServices } from "../../gestion-de-endpoints/useIncluyeServices"
import GestionBusqueda from "../../gestion-de-endpoints/GestionBusqueda"
import CategoriasServices from "../../gestion-de-endpoints/useCategoriasServices"
import { useRouter } from "next/router"

export default function ActividadesYTurismo() {
  const router = useRouter()
  const query = router.query

  const [fecha_ini, setFecha_ini] = useState(query.fechaActual)
  const [fecha_fina, setFecha_fina] = useState(query.fechaFinal)
  const [incluye, setIncluye] = useState("")
  const [actividades, setAactividades] = useState("")
  const [categoria, setCategoria] = useState(
    query?.categoria ? query?.categoria : ""
  )
  console.log(query)
  const [disable, setDisable] = useState("")
  const { dataCategoria, loadingCategoria } = CategoriasServices()
  const { db: dataActividades, loadingGetData: loadingActiviades } =
    useActividadesServices()
  const { db: dataIncluye, loadingGetData: loadingIncluye } =
    useIncluyeServices()
  const { dataTours, loading: loadingGetTour } = GestionTours()
  const [itemsTours, setItemsTours] = useState([])
  const { dataBusqueda, getBusquedaAvanzada, loadingBusqueda } =
    GestionBusqueda({
      fecha_ini: fecha_ini,
      fecha_fina: fecha_fina,
      incluye: incluye,
      actividades: actividades,
      categoria_slug: categoria,
      precio_base: "",
      horas: "",
      dias: "",
      page: 1,
      numberPaginate: 12,
    })

  useEffect(() => {
    setFecha_ini(query.fechaActual)
    setFecha_fina(query.fechaFinal)
    setIncluye(query.incluye ? query.incluye : "")
    setAactividades(query.actividades ? query.actividades : "")
    setCategoria(query.categoria ? query.categoria : "")
  }, [query])

  useEffect(() => {
    if (!loadingBusqueda) {
      setItemsTours(dataBusqueda)
    }
  }, [loadingGetTour])

  useEffect(() => {
    getBusquedaAvanzada()
    if (
      fecha_ini !== "" ||
      fecha_fina !== "" ||
      incluye !== "" ||
      actividades !== "" ||
      categoria !== ""
    ) {
      setDisable(true)
    } else {
      setDisable(false)
    }
  }, [fecha_ini, fecha_fina, incluye, actividades, categoria])

  const buscar = () => {
    setItemsTours(dataBusqueda)
  }

  const quitar = () => {
    setItemsTours(dataTours)
    setFecha_ini("")
    setFecha_fina("")
    setCategoria("")
    setIncluye("")
    setAactividades("")
  }
  const updateRouter = (name, valor) => {
    if (valor.length === 0) {
      const { [name]: toDelete, ...res } = query
      router.replace({
        query: {
          ...res,
        },
      })
    } else {
      router.replace({
        query: {
          ...query,
          [name]: valor,
        },
      })
    }
  }

  return (
    <div className='busqueda-page'>
      <Head>
        <title>Actividades y turismo - Enlace mundial</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/hamburgers/1.1.3/hamburgers.min.css'
        />
      </Head>

      <main>
        <section className='container mt-5 px-4 px-md-0'>
          <div className='row'>
            <div className='col-12'>
              <div className='d-flex justify-content-between align-items-center'>
                <h3 className='subtitulo-slug text-secondary text-left'>
                  {query.nombreDepartamento
                    ? `Tours a región ${query.nombreDepartamento}`
                    : "Tours a regiones del Perú"}
                </h3>

                {/* Solo desktop */}
                <div className='d-none d-md-block'>
                  <span className='d-inline-block mr-3'>Crucero</span>
                  <span>Inicio</span>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className='container mt-4 mt-md-5 px-4 px-md-0'>
          <div className='row'>
            <div className='col-md-3'>
              <aside>
                <button
                  type='button'
                  className='btn btn-primary btn-block font-weight-bold'
                  disabled={disable ? false : true}
                  onClick={buscar}
                >
                  Buscar
                </button>
                <button
                  type='button'
                  className='btn btn-primary btn-block font-weight-bold'
                  onClick={quitar}
                >
                  Quitar filtros
                </button>

                <div className='card bg-light border-0 rounded-0 mt-4'>
                  <div className='card-body pb-1'>
                    <h3 className='card-title stext-secondary font-weight-bold'>
                      Disponibilidad de salidas
                    </h3>

                    <div className='form-group'>
                      <label htmlFor='fechaInicial' className='text-secondary'>
                        Desde
                      </label>
                      <input
                        type='date'
                        className='form-control rounded-0'
                        value={fecha_ini}
                        name='fecha_ini'
                        onChange={(e) => {
                          setFecha_ini(e.target.value)
                          updateRouter("fechaActual", e.target.value)
                        }}
                      />
                    </div>

                    <div className='form-group'>
                      <label htmlFor='fechaInicial' className='text-secondary'>
                        Hasta
                      </label>
                      <input
                        type='date'
                        className='form-control rounded-0'
                        value={fecha_fina}
                        name='fecha_fina'
                        onChange={(e) => {
                          setFecha_fina(e.target.value)
                          updateRouter("fechaFinal", e.target.value)
                        }}
                      />
                    </div>
                  </div>
                </div>

                <div className='mt-4'>
                  <h3 className='card-title stext-secondary font-weight-bold mt-3'>
                    Categorias
                  </h3>
                  {loadingCategoria ? (
                    <p>Cargando ...</p>
                  ) : (
                    dataCategoria.map((item) => {
                      return (
                        <div className='form-check' key={item?.categoriaId}>
                          <input
                            id={item?.categoriaId}
                            className='form-check-input'
                            type='radio'
                            name='categorias'
                            value={item?.slugCategoria}
                            checked={
                              categoria == item?.slugCategoria ? true : false
                            }
                            onChange={(e) => {
                              setCategoria(e.target.value)
                              updateRouter("categoria", e.target.value)
                            }}
                          />
                          <label
                            className='form-check-label'
                            htmlFor={item?.categoriaId}
                          >
                            {item?.tituloCategoria}
                          </label>
                        </div>
                      )
                    })
                  )}
                </div>

                {/* Solo desktop */}
                <section className='  d-md-block'>
                  {/* <h4 className='card-subtitle font-weight-bold'>
                    Tours de último minuto
                  </h4>

                  <div className='mt-3'>
                    <div className='form-check'>
                      <input
                        className='form-check-input'
                        type='radio'
                        name='disponibles'
                        id='disponible-1'
                        value='option1'
                      />
                      <label
                        className='form-check-label text-muted'
                        htmlFor='disponible-1'
                      >
                        Disponibles hoy o mañana
                      </label>
                    </div>

                    <div className='form-check'>
                      <input
                        className='form-check-input'
                        type='radio'
                        name='disponibles'
                        id='disponible-2'
                        value='option1'
                      />
                      <label
                        className='form-check-label text-muted'
                        htmlFor='disponible-2'
                      >
                        Disponibles hoy o mañana o pasado
                      </label>
                    </div>
                  </div> */}

                  <div className='mt-3'>
                    {/* <h3 className='card-title stext-secondary font-weight-bold'>
                      Destinos en Perú
                    </h3>

                    <h3 className='card-title stext-secondary font-weight-bold'>
                      Perú
                    </h3>

                    <div className='form-check'>
                      <input
                        className='form-check-input'
                        type='checkbox'
                        value=''
                        id='destino-padre'
                      />
                      <label
                        className='form-check-label'
                        htmlFor='destino-padre'
                      >
                        Cusco
                      </label>
                    </div>

                    <div className='mt-1 px-3'>
                      <div className='form-check'>
                        <input
                          className='form-check-input'
                          type='checkbox'
                          value=''
                          id='destino-hijo'
                        />
                        <label
                          className='form-check-label'
                          htmlFor='destino-hijo'
                        >
                          Tours a Cusco
                        </label>
                      </div>
                    </div> */}
                    {/* Incluye */}
                    <h3 className='card-title stext-secondary font-weight-bold mt-3'>
                      Incluye
                    </h3>
                    {loadingIncluye ? (
                      <p>Cargando ...</p>
                    ) : (
                      dataIncluye.map((item) => {
                        return (
                          <div className='form-check' key={item?.incluyeId}>
                            <input
                              id={item?.incluyeId}
                              className='form-check-input'
                              type='radio'
                              name='incluye'
                              value={item?.descripcionIncluye}
                              checked={
                                incluye == item?.descripcionIncluye
                                  ? true
                                  : false
                              }
                              onChange={(e) => {
                                setIncluye(e.target.value)
                                updateRouter("incluye", e.target.value)
                              }}
                            />
                            <label
                              className='form-check-label'
                              htmlFor={item?.incluyeId}
                            >
                              {item?.descripcionIncluye}
                            </label>
                          </div>
                        )
                      })
                    )}
                    {/* Actividades */}
                    <h3 className='card-title stext-secondary font-weight-bold mt-3'>
                      Actividades
                    </h3>
                    {loadingActiviades ? (
                      <p>Cargando ...</p>
                    ) : (
                      dataActividades.map((item) => {
                        return (
                          <div className='form-check' key={item?.actividadId}>
                            <input
                              id={item?.actividadId}
                              className='form-check-input'
                              type='radio'
                              name='actividades'
                              value={item?.descripcion_actividad}
                              checked={
                                actividades == item?.descripcion_actividad
                                  ? true
                                  : false
                              }
                              onChange={(e) => {
                                setAactividades(e.target.value)
                                updateRouter("actividades", e.target.value)
                              }}
                            />
                            <label
                              className='form-check-label'
                              htmlFor={item?.actividadId}
                            >
                              {item?.descripcion_actividad}
                            </label>
                          </div>
                        )
                      })
                    )}
                  </div>
                </section>
              </aside>
            </div>

            <div className='col-md-9 mt-4 mt-md-0'>
              {itemsTours.length !== 0 ? (
                itemsTours.map((item) => {
                  return <CardBusqueda item={item} key={item.tourId} />
                })
              ) : (
                <div className='d-flex justify-content-center'>
                  <p className='text-md'>No hay Resultados</p>
                </div>
              )}
            </div>
          </div>
        </section>
        <div className='hidden'></div>
      </main>

      <Script
        src='https://kit.fontawesome.com/3bd84f9f96.js'
        crossorigin='anonymous'
      />
    </div>
  )
}
