import React, { useState, useRef } from "react"
import { useRouter } from "next/router"
import Head from "next/head"
import Link from "next/link"

import posts from "../../datos-paginas/api/blog"

import Swiper from "react-id-swiper"
import Gallery from "components/gallery/index"
import ToursRelacionados from "components/luna-de-miel/tours-relacionados"
import ModalContacto from "components/general/modal-contacto"
import MenuInterior from "@/components/servicios/submenu"
import RedesSociales from "@/components/general/redes-sociales"
import CardBlog from "@/components/cards/card-blog"

import styles from "./styles.module.scss"

export default function Home() {
  const router = useRouter()
  let slug = router.query.slug

  console.log(slug)
  // console.log(router)
  const post = {
    imagen:
      "https://i1.wp.com/instyle.mx/wp-content/uploads/2019/07/parejas-felices.jpg",
    titulo: "Y tú qué planes? Turismo, ofertas de viaje y tours por el Perú",
    descripcion:
      "Conoce el Perú! Te invitamos a que viajes y descubras los destinos, actividades y planes en el Perú que aún no conoces.",
    descripcion_larga:
      "Conoce el Perú! Te invitamos a que viajes y descubras los destinos, actividades y planes en el Perú que aún no conoces. Conoce el Perú! Te invitamos a que viajes y descubras los destinos, actividades y planes en el Perú que aún no conoces.Conoce el Perú! Te invitamos a que viajes y descubras los destinos, actividades y planes en el Perú que aún no conoces.Conoce el Perú! Te invitamos a que viajes y descubras los destinos, actividades y planes en el Perú que aún no conoces.Conoce el Perú! Te invitamos a que viajes y descubras los destinos, actividades y planes en el Perú que aún no conoces.Conoce el Perú! Te invitamos a que viajes y descubras los destinos, actividades y planes en el Perú que aún no conoces.",
  }

  const [destacados, setDestacados] = useState(posts)

  const categorias = [
    {
      id: 1,
      nombre: "Lugares turísticos en Lima",
    },
    {
      id: 2,
      nombre: "Hoteles en Arequipa",
    },
    {
      id: 3,
      nombre: "Lugares turísticos en Cusco",
    },
    {
      id: 4,
      nombre: "Hoteles en La libertad",
    },
  ]

  const tags = [
    {
      id: 1,
      nombre: "Lima",
    },
    {
      id: 2,
      nombre: "Arequipa",
    },
    {
      id: 3,
      nombre: "Cusco",
    },
    {
      id: 4,
      nombre: "La libertad",
    },
  ]

  // Swiper
  const swiperRef = useRef(null)

  const carouselParams = {
    slidesPerView: 1,
    loop: true,
  }

  return (
    <div>
      <Head>
        <title>{slug} - Enlace mundial</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/hamburgers/1.1.3/hamburgers.min.css'
        />
      </Head>

      <main className={styles.slug}>
        <section className='l-miel__items mt-4'>
          <div className='container'>
            <div className='row'>
              <div className='col-md-12'>
                <span className='small text-primary'>Blog / {post.titulo}</span>
              </div>
            </div>
          </div>

          {/* Info */}
          <section className='container mt-5'>
            <div className='row justify-content-between'>
              <article className='col-md-9 mt-3 mt-md-0 pr-md-5'>
                <h2 className={styles.slug_titulo}>{post.titulo}</h2>

                <section
                  style={{ backgroundImage: "url(" + post.imagen + ")" }}
                  className={`${styles.slug_imagen} mt-4`}
                ></section>

                <section className='mt-3'>
                  <p>{post.descripcion_larga}</p>
                  <p>{post.descripcion_larga}</p>
                  <p>{post.descripcion_larga}</p>
                </section>

                <div className='mt-3'>
                  <RedesSociales />
                </div>
              </article>

              <aside className='col-md-3'>
                {/* Buscador */}
                <section>
                  <form>
                    <label htmlFor='search' className={styles.slug_subtitulo}>
                      Buscar
                    </label>
                    <input
                      type='search'
                      id='search'
                      className='form-control py-4'
                    />
                  </form>

                  {/* Categorías */}
                  <section className='mt-4'>
                    <h3 className={styles.slug_subtitulo}>Categorías</h3>

                    <ul className='list-unstyled mt-3'>
                      {categorias.map((c) => {
                        return (
                          <li key={c.id} className='mt-1'>
                            <Link
                              href={`/blog/categorias/${c.nombre}`}
                              passHref
                            >
                              <a className='text-primary text-decoration-none'>
                                <i className='fas fa-chevron-right'></i>
                                <span className='ml-2'>{c.nombre}</span>
                              </a>
                            </Link>
                          </li>
                        )
                      })}
                    </ul>
                  </section>

                  {/* Tags */}
                  <section className='mt-4'>
                    <h3 className={styles.slug_subtitulo}>Etiquetas</h3>

                    <ul className='d-flex flex-wrap list-unstyled mt-3'>
                      {tags.map((c) => {
                        return (
                          <li key={c.id} className='mt-2 mr-2'>
                            <Link href={`/blog/etiquetas/${c.nombre}`} passHref>
                              <a className={styles.slug_tag}>{c.nombre}</a>
                            </Link>
                          </li>
                        )
                      })}
                    </ul>
                  </section>

                  {/* Destacados */}
                  <section className='mt-4'>
                    <h3 className={styles.slug_subtitulo}>
                      Te puede interesar
                    </h3>

                    <div className='mt-3'>
                      <Swiper ref={swiperRef} {...carouselParams}>
                        {destacados.map((item) => {
                          return (
                            <div key={item.id}>
                              <CardBlog item={item} />
                            </div>
                          )
                        })}
                      </Swiper>
                    </div>
                  </section>
                </section>
              </aside>
            </div>
          </section>
        </section>
      </main>
    </div>
  )
}
