import React, { useState, useRef } from "react"
import { useRouter } from "next/router"
import Head from "next/head"
import Link from "next/link"

import posts from "../../datos-paginas/api/blog"

import CardBlog from "@/components/cards/card-blog"

import styles from "./styles.module.scss"

export default function Home() {
  const router = useRouter()

  const [items, setItems] = useState(posts)

  const categorias = [
    {
      id: 1,
      nombre: "Lugares turísticos en Lima",
      imagenPrincipal:
        "https://www.iperu.org/wp-content/uploads/2016/01/plaza-de-armas-de-lima.jpg",
    },
    {
      id: 2,
      nombre: "Hoteles en Arequipa",
      imagenPrincipal:
        "https://media-cdn.tripadvisor.com/media/photo-s/17/9d/a1/a2/pool.jpg",
    },
    {
      id: 3,
      nombre: "Lugares turísticos en Cusco",
      imagenPrincipal:
        "https://www.paquetesdeviajesperu.com/wp-content/uploads/2019/04/ciudad-cusco-peru-1.jpg",
    },
    {
      id: 4,
      nombre: "Hoteles en La libertad",
      imagenPrincipal:
        "https://1.bp.blogspot.com/-TcAASy4riJ4/WR9WDa10YwI/AAAAAAAAD1o/_E2rUhdXpsw1nv1_3a9eG-pDqP7oa23TgCLcB/s1600/37785994.jpg",
    },
  ]

  let slug = router.query.slug

  // Swiper
  const swiperRef = useRef(null)

  const carouselParams = {
    slidesPerView: 1,
    loop: true,
  }

  return (
    <div>
      <Head>
        <title>{slug} - Enlace mundial</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/hamburgers/1.1.3/hamburgers.min.css'
        />
      </Head>

      <main className={styles.blog}>
        <section className='mt-4'>
          <div className='container'>
            <div className='row'>
              <div className='col-md-12'>
                <span className='small text-primary'>Blog</span>
              </div>
            </div>
          </div>

          {/* Info */}
          <section className='container mt-5'>
            <div className='row'>
              <div className='col'>
                <h2 className={styles.slug_titulo}>Publicaciones recientes</h2>
              </div>
            </div>
            <div className='row mt-4'>
              {items.map((item) => {
                return (
                  <div key={item.id} className='col-md-4'>
                    <CardBlog item={item} />
                  </div>
                )
              })}
            </div>
            <div className='row mt-3'>
              {items.map((item) => {
                return (
                  <div key={item.id} className='col-md-4'>
                    <CardBlog item={item} />
                  </div>
                )
              })}
            </div>
          </section>

          <section className='container mt-5'>
            <div className='row'>
              <div className='col'>
                <h2 className={styles.slug_titulo}>Categorías</h2>
              </div>
            </div>
            <div className='row mt-4'>
              {categorias.map((item) => {
                return (
                  <div key={item.id} className='col-md-4 mb-3'>
                    <article>
                      <div
                        style={{
                          backgroundImage: `url("${item.imagenPrincipal}")`,
                          backgroundSize: "cover",
                          height: "200px",
                        }}
                        className={styles.blog_categoria}
                      ></div>
                      <Link href={`/blog/categorias/${item.nombre}`} passHref>
                        <a className='lead'>{item.nombre}</a>
                      </Link>
                    </article>
                  </div>
                )
              })}
            </div>
          </section>
        </section>
      </main>
    </div>
  )
}
