import React from "react"
import { useRouter } from "next/router"
import Head from "next/head"
import Link from "next/link"

import Gallery from "components/gallery/index"
import ToursRelacionados from "components/luna-de-miel/tours-relacionados"
import ModalContacto from "components/general/modal-contacto"
import MenuInterior from "@/components/servicios/submenu"
import { GET_SLUG_CRUCERO, URL } from "../../endpoints y url/endpoints"
import request from "graphql-request"
export async function getServerSideProps({ params }) {
  const res = await request(URL, GET_SLUG_CRUCERO, {
    slugCrucero: params.slug,
  })
  const data = res?.GetSlugCrucero
  return {
    props: {
      data: data,
    },
  }
}

export default function Home({ data }) {
  console.log(data)
  const router = useRouter()

  let slug = router.query.slug
  console.log(slug)

  return (
    <div>
      <Head>
        <title>{slug} - Enlace mundial</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/hamburgers/1.1.3/hamburgers.min.css'
        />
      </Head>

      <main className='l-miel'>
        <section className='l-miel__items mt-3'>
          <div className='container'>
            <div className='row'>
              <div className='col-md-12'>
                <span className='small text-primary'>Viaje en crucero</span>
                <h2 className='subtitulo-slug text-primary'>
                  {data?.tituloCrucero}
                </h2>
              </div>
            </div>
            <div className='row'></div>
          </div>

          <MenuInterior />

          {/* Info */}
          <section className='container mt-5'>
            <div className='row'>
              <div className='col-md-8'>
                <Gallery imagenes={data?.galeriaCrucero} />
              </div>
            </div>
          </section>

          {/* Detalles */}
          <section>
            <div className='container-fluid bg-light mt-4 py-2'>
              <div className='row'>
                <div className='col-md-8'>
                  <h2 className='subtitulo-general text-uppercase my-0'>
                    Detalles
                  </h2>
                </div>
              </div>
            </div>

            <div className='container mt-4'>
              <div className='row'>
                <div className='col-md-8'>
                  <div className='card'>
                    <div className='card-body'>
                      <h5 className='card-title font-weight-bold'>{slug}</h5>

                      <div className='py-2 px-3'>
                        <p className='card-text'>
                          Some quick example text to build on the card title and
                          make up the bulk of the card's content.
                        </p>
                      </div>
                    </div>
                  </div>

                  <div className='card mt-4'>
                    <div className='card-body'>
                      <h5 className='card-title font-weight-bold'>
                        Punto de partida
                      </h5>

                      <div className='py-2 px-3'>
                        <p className='card-text'>
                          Some quick example text to build on the card title and
                          make up the bulk of the card's content.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Itinerario */}
          <section>
            <div className='container-fluid bg-light mt-4 py-2'>
              <div className='row'>
                <div className='col-md-8'>
                  <h2 className='subtitulo-general text-uppercase my-0'>
                    Itinerario
                  </h2>
                </div>
              </div>
            </div>

            <div className='container mt-4'>
              <div className='row'>
                <div className='col-md-8'>
                  <div className='card'>
                    <div className='card-body'>
                      <h5 className='card-title text-secondary font-weight-bold'>
                        Itinerario
                      </h5>

                      <div className='py-2'>
                        <ul className='list-unstyled'>
                          {data.itinerarioCrucero.split(",").map((item) => {
                            return (
                              <li
                                className='l-miel-itinerario__list-item d-flex mb-2'
                                key={item}
                              >
                                <span className='text-primary d-inline-block mr-2'>
                                  <i className='fas fa-check'></i>
                                </span>
                                {item}
                              </li>
                            )
                          })}
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Incluye */}
          <section>
            <div className='container-fluid bg-light mt-4 py-2'>
              <div className='row'>
                <div className='col-md-8'>
                  <h2 className='subtitulo-general text-uppercase my-0'>
                    Incluye
                  </h2>
                </div>
              </div>
            </div>

            <div className='container mt-4'>
              <div className='row'>
                <div className='col-md-8'>
                  <div className='card'>
                    <div className='card-body'>
                      <h5 className='card-title text-secondary font-weight-bold'>
                        Incluye
                      </h5>

                      <div className='py-2'>
                        <ul className='list-unstyled'>
                          {data.incluyeCrucero.split(",").map((item) => {
                            return (
                              <li
                                className='l-miel-itinerario__list-item d-flex mb-2'
                                key={item}
                              >
                                <span className='text-primary d-inline-block mr-2'>
                                  <i className='far fa-check-circle'></i>
                                </span>
                                {item}
                              </li>
                            )
                          })}
                        </ul>
                      </div>

                      <h5 className='card-title text-secondary font-weight-bold'>
                        No incluye
                      </h5>

                      <div className='py-2'>
                        <ul className='list-unstyled'>
                          {data.noIncluyeCrucero.split(",").map((item) => {
                            return (
                              <li
                                className='l-miel-itinerario__list-item d-flex mb-2'
                                key={item}
                              >
                                <span className='text-danger d-inline-block mr-2'>
                                  <i className='far fa-check-circle'></i>
                                </span>
                                {item}
                              </li>
                            )
                          })}
                        </ul>
                      </div>
                    </div>
                  </div>

                  <div className='card mt-4'>
                    <div className='card-body'>
                      <h5 className='card-title text-secondary font-weight-bold'>
                        Actividades
                      </h5>

                      <div className='py-2'>
                        <ul className='list-unstyled'>
                          {data.actividadesCrucero.split(",").map((item) => {
                            return (
                              <li
                                className='l-miel-itinerario__list-item d-flex mb-2'
                                key={item}
                              >
                                <span className='text-primary d-inline-block mr-2'>
                                  <i className='far fa-check-circle'></i>
                                </span>
                                {item} (Incluida)
                              </li>
                            )
                          })}
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Notas */}
          <section>
            <div className='container-fluid bg-light mt-4 py-2'>
              <div className='row'>
                <div className='col-md-8'>
                  <h2 className='subtitulo-general text-uppercase my-0'>
                    Notas
                  </h2>
                </div>
              </div>
            </div>

            <div className='container mt-4'>
              <div className='row'>
                <div className='col-md-8'>
                  <div className='card'>
                    <div className='card-body'>
                      <h5 className='card-title text-secondary font-weight-bold'>
                        Notas
                      </h5>

                      <div className='py-2'>
                        <ul className='list-unstyled'>
                          {data.notasCrucero.split(",").map((item) => {
                            return (
                              <li
                                className='l-miel-itinerario__list-item d-flex mb-2'
                                key={item}
                              >
                                <span className='text-primary d-inline-block mr-2'>
                                  <i className='fas fa-check'></i>
                                </span>
                                {item}
                              </li>
                            )
                          })}
                        </ul>
                      </div>
                    </div>
                  </div>

                  <div className='card mt-4'>
                    <div className='card-body'>
                      <h5 className='card-title text-secondary font-weight-bold'>
                        Políticas de cancelación
                      </h5>

                      <div className='py-2'>
                        {data?.politicasCrucero.split(",").map((item) => (
                          <p>{item}</p>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Notas */}
          <section>
            <div className='bg-light mt-4 py-2'>
              <div className='container'>
                <div className='row'>
                  <div className='col-md-8'>
                    <h2 className='subtitulo-general text-uppercase text-left my-0'>
                      Cruceros similares
                    </h2>
                  </div>
                </div>
              </div>
            </div>

            <div className='container'>
              <div className='row'>
                <div className='col-md-8'>
                  <ToursRelacionados />
                </div>
              </div>
            </div>
          </section>

          <ModalContacto />
        </section>
      </main>
    </div>
  )
}
