import React, { useEffect } from "react"

import Head from "next/head"
import Script from "next/script"
import { useScreenContext } from '../../context/screen'
import Banner from "@/components/cruceros/banner"
import gestionCrucero from "../../gestion-de-endpoints/gestionCrucero.js"
import request from "graphql-request"
import CardGeneralCrucero from "../../components/cards/card-general-crucero"

export default function Home() {
  const { dataCrucero, loading: loadingGetCrucero } = gestionCrucero()
  const { DispatchScreen } = useScreenContext()
  
  useEffect(() => {
    DispatchScreen({ type: 'ChangeSubTittle', payload: 'Cruceros' })
  }, [])
  return (
    <div>
      {/* <Head>
        <title>Cruceros - Enlace mundial</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/hamburgers/1.1.3/hamburgers.min.css'
        />
      </Head> */}

      <main>
        <Banner />
        <section className='container carousel-app'>
          <div className='row'>
            <div className='col-md-12'>
              <h2 className='subtitulo-general subtitulo-general--border-bottom'>Viaje en crucero</h2>
            </div>
          </div>

          <div className='row mt-4'>
            {loadingGetCrucero ? (
              <p>Cargando ...</p>
            ) : (
              dataCrucero.map((item) => {
                return (
                  <div className='col-md-4 mb-5' key={item.cruceroId}>
                    <CardGeneralCrucero item={item} />
                  </div>
                )
              })
            )}
          </div>
        </section>
      </main>

      <Script
        src='https://kit.fontawesome.com/3bd84f9f96.js'
        crossorigin='anonymous'
      />
    </div>
  )
}
